(()=>{
const U='https://vgurvbdbpxcgkhmunlxr.supabase.co',K='sb_publishable_Dlgj0c5D_PVKP0h7x6GZ4w_BssxbIoj',ART=U+'/rest/v1/artilheiros',MATCH=U+'/rest/v1/team_rank_matches',H={apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json'};
const TEAMS=['FENIX','RAFAGEMER','LOBO MAU','REAL MADRI','BARCELONA','ATLETICO DE MADRI','XV DE PIRACICABA','KATATUMBA','VERA CRUZ','NAPOLI','FIORENTINA','CRISTIAN SORTE'];let matches=[],rows=[],unlocked=false;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const CKEY='bomba_petch_rank_cumulative_v1',SKEY='bomba_petch_rank_last_saved_v1';
function blankMatch(){return {id:null,team_a:'',score_a:0,score_b:0,team_b:''}}
function cloneMatches(a){return a.map(m=>({team_a:String(m.team_a||'').trim(),score_a:Math.max(0,+m.score_a||0),score_b:Math.max(0,+m.score_b||0),team_b:String(m.team_b||'').trim()}))}
function getStored(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(e){return null}}
function putStored(key,v){localStorage.setItem(key,JSON.stringify(v))}
function emptyStats(){let s={};TEAMS.forEach(t=>s[t]={team:t,j:0,v:0,e:0,d:0,sg:0,pts:0});return s}
function calcStats(list){let s=emptyStats();list.forEach(m=>{let a=String(m.team_a||'').trim().toUpperCase(),b=String(m.team_b||'').trim().toUpperCase();if(!a||!b||a===b)return;if(!s[a])s[a]={team:a,j:0,v:0,e:0,d:0,sg:0,pts:0};if(!s[b])s[b]={team:b,j:0,v:0,e:0,d:0,sg:0,pts:0};let x=Math.max(0,+m.score_a||0),y=Math.max(0,+m.score_b||0);s[a].j++;s[b].j++;s[a].sg+=x-y;s[b].sg+=y-x;if(x>y){s[a].v++;s[b].d++;s[a].pts+=3;s[b].pts--}else if(y>x){s[b].v++;s[a].d++;s[b].pts+=3;s[a].pts--}else{s[a].e++;s[b].e++;s[a].pts++;s[b].pts++}});return s}
function ensureCumulative(){let c=getStored(CKEY),last=getStored(SKEY);if(!c){c=calcStats(matches);putStored(CKEY,c)}if(!last){last=cloneMatches(matches);putStored(SKEY,last)}return c}
function cumulative(){return ensureCumulative()}
function applyDelta(oldList,newList){let c=calcStats(oldList),n=calcStats(newList),base=cumulative();Object.keys(base).forEach(k=>{if(!base[k])base[k]={team:k,j:0,v:0,e:0,d:0,sg:0,pts:0};base[k].j-=c[k]?.j||0;base[k].v-=c[k]?.v||0;base[k].e-=c[k]?.e||0;base[k].d-=c[k]?.d||0;base[k].sg-=c[k]?.sg||0;base[k].pts-=c[k]?.pts||0;base[k].j+=n[k]?.j||0;base[k].v+=n[k]?.v||0;base[k].e+=n[k]?.e||0;base[k].d+=n[k]?.d||0;base[k].sg+=n[k]?.sg||0;base[k].pts+=n[k]?.pts||0});Object.keys(n).forEach(k=>{if(!base[k])base[k]=n[k]});putStored(CKEY,base);putStored(SKEY,cloneMatches(newList));return base}
function css(){if(document.getElementById('rankFixCss'))return;let s=document.createElement('style');s.id='rankFixCss';s.textContent='.rfbox{background:#121720;border:1px solid #29313d;border-radius:15px;padding:20px}.rfgrid{display:grid;gap:10px}.rfmatch{display:grid;grid-template-columns:45px 1fr 70px 20px 70px 1fr;gap:8px;align-items:center}.rftable{width:100%;border-collapse:collapse;min-width:700px}.rftable th,.rftable td{padding:12px;border-bottom:1px solid #29313d;text-align:center}.rftable th{color:#ff7300}.rfwrap{overflow:auto}.rfpass{position:fixed;inset:0;background:#000d;z-index:99999;display:flex;align-items:center;justify-content:center;padding:20px}.rfpass>div{background:#121720;border:1px solid #343b47;border-radius:16px;padding:25px;width:min(430px,100%)}@media(max-width:650px){.rfmatch{grid-template-columns:25px 1fr 50px 12px 50px 1fr}.rfmatch input{padding:9px 4px;font-size:12px}}';document.head.appendChild(s)}
function password(){if(unlocked)return true;css();let first=!localStorage.getItem('bomba_petch_artilheiros_password'),o=document.createElement('div');o.className='rfpass';o.innerHTML='<div><h2 class="orange">🔐 '+(first?'Criar senha dos Artilheiros':'Artilheiros')+'</h2><p class="muted">'+(first?'Escolha uma senha para proteger esta aba.':'Digite sua senha para entrar.')+'</p><input id="rfp1" class="input" type="password" placeholder="Senha"><input id="rfp2" class="input" type="password" placeholder="Confirmar senha" style="display:'+(first?'block':'none')+'"><div id="rfe" class="muted" style="min-height:25px"></div><button id="rfc" class="btn">Cancelar</button> <button id="rfo" class="btn primary">'+(first?'Criar senha':'Entrar')+'</button></div>';document.body.appendChild(o);o.querySelector('#rfc').onclick=()=>o.remove();o.querySelector('#rfo').onclick=()=>{let p=o.querySelector('#rfp1').value,e=o.querySelector('#rfe');if(p.length<4){e.textContent='A senha precisa ter pelo menos 4 caracteres.';return}if(first&&p!==o.querySelector('#rfp2').value){e.textContent='As senhas não são iguais.';return}if(first){localStorage.setItem('bomba_petch_artilheiros_password',p);unlocked=true;o.remove();showArt()}else if(p===localStorage.getItem('bomba_petch_artilheiros_password')){unlocked=true;o.remove();showArt()}else e.textContent='Senha incorreta.'};return false}
async function loadArt(){try{let r=await fetch(ART+'?select=id,player_name,goals&order=id.asc',{headers:H,cache:'no-store'});rows=r.ok?await r.json():[]}catch(e){rows=[]}while(rows.length<30)rows.push({id:null,player_name:'',goals:0});let g=document.getElementById('artGrid');if(g)g.innerHTML=rows.slice(0,30).map((x,i)=>'<label class="slot"><span class="num">'+(i+1)+'</span><input class="input an" value="'+esc(x.player_name)+'" placeholder="Nome do jogador"><input class="input ag" type="number" min="0" value="'+(+x.goals||0)+'" placeholder="Gols" style="max-width:120px"></label>').join('')}
async function saveArt(){let n=document.querySelectorAll('.an'),g=document.querySelectorAll('.ag');for(let i=0;i<n.length;i++){let x=rows[i],b={player_name:n[i].value.trim(),goals:Math.max(0,+g[i].value||0),updated_at:new Date().toISOString()};if(x.id)await fetch(ART+'?id=eq.'+x.id,{method:'PATCH',headers:H,body:JSON.stringify(b)});else if(b.player_name)await fetch(ART,{method:'POST',headers:H,body:JSON.stringify(b)})}loadArt()}
function stats(){let c=cumulative();return Object.values(c).sort((a,b)=>b.pts-a.pts||b.sg-a.sg||b.v-a.v||TEAMS.indexOf(a.team)-TEAMS.indexOf(b.team))}
function rankUI(){let m=document.getElementById('rankMatches');if(!m)return;m.innerHTML=matches.map((x,i)=>'<div class="rfmatch"><b class="orange">J'+(i+1)+'</b><input class="input ra" value="'+esc(x.team_a||'')+'" placeholder="TIME A"><input class="input rsa" type="number" min="0" value="'+(+x.score_a||0)+'"><b>×</b><input class="input rsb" type="number" min="0" value="'+(+x.score_b||0)+'"><input class="input rb" value="'+esc(x.team_b||'')+'" placeholder="TIME B"></div>').join('')}
function rankTable(){let t=document.getElementById('rankBody');if(!t)return;t.innerHTML=stats().map((x,i)=>'<tr><td>'+(i+1)+'</td><td style="text-align:left"><b>'+esc(x.team)+'</b></td><td>'+x.j+'</td><td>'+x.v+'</td><td>'+x.e+'</td><td>'+x.d+'</td><td>'+(x.sg>=0?'+':'')+x.sg+'</td><td class="points">'+x.pts+'</td></tr>').join('')}
async function loadRank(){try{let r=await fetch(MATCH+'?select=id,team_a,score_a,score_b,team_b&order=id.asc',{headers:H,cache:'no-store'});matches=r.ok?await r.json():[]}catch(e){matches=[]}while(matches.length<12)matches.push(blankMatch());matches=matches.slice(0,12);ensureCumulative();rankUI();rankTable()}
async function saveRank(){let old=getStored(SKEY)||cloneMatches(matches),a=document.querySelectorAll('.ra'),b=document.querySelectorAll('.rb'),x=document.querySelectorAll('.rsa'),y=document.querySelectorAll('.rsb'),next=[];for(let i=0;i<12;i++){let body={team_a:a[i].value.trim(),score_a:Math.max(0,+x[i].value||0),score_b:Math.max(0,+y[i].value||0),team_b:b[i].value.trim(),updated_at:new Date().toISOString()};next.push(body);let m=matches[i];if(m.id)await fetch(MATCH+'?id=eq.'+m.id,{method:'PATCH',headers:H,body:JSON.stringify(body)});else if(body.team_a&&body.team_b){let rr=await fetch(MATCH,{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(body)});if(rr.ok){let z=await rr.json();if(z[0])matches[i]={...body,id:z[0].id}}}}applyDelta(old,next);loadRank()}
async function resetRank(){if(!confirm('Resetar somente o registro das partidas? A tabela acumulada NÃO será apagada.'))return;for(let m of matches)if(m.id)await fetch(MATCH+'?id=eq.'+m.id,{method:'PATCH',headers:H,body:JSON.stringify({team_a:'',score_a:0,score_b:0,team_b:''})});loadRank()}
function showArt(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('artilheiros').classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='artilheiros'));loadArt()}
function showRank(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('rank-times').classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='rank-times'));loadRank()}
function add(){css();let nav=document.getElementById('nav'),main=document.querySelector('main.wrap');if(!nav||!main)return;if(!document.getElementById('artNav')){let b=document.createElement('button');b.id='artNav';b.dataset.page='artilheiros';b.textContent='⚽ Artilheiros';b.onclick=()=>password();nav.appendChild(b)}if(!document.getElementById('rankNav')){let b=document.createElement('button');b.id='rankNav';b.dataset.page='rank-times';b.textContent='🏆 RANK DOS TIMES';b.onclick=showRank;nav.appendChild(b)}if(!document.getElementById('artilheiros')){let s=document.createElement('section');s.id='artilheiros';s.className='page';s.innerHTML='<h1>⚽ Artilheiros</h1><p class="muted">Cadastre o nome do jogador e a quantidade de gols.</p><div class="rfbox"><div id="artGrid" class="slots"></div><div class="savebar"><button class="btn primary" id="saveArt">💾 Salvar artilheiros</button><span id="artMsg" class="ok"></span></div></div>';main.appendChild(s);s.querySelector('#saveArt').onclick=()=>{if(!unlocked)password();else saveArt()}}if(!document.getElementById('rank-times')){let s=document.createElement('section');s.id='rank-times';s.className='page';s.innerHTML='<h1>🏆 RANK DOS TIMES</h1><p class="muted">Classificação acumulada dos times.</p><div class="rfbox"><h2>⚽ REGISTRO DE 12 PARTIDAS</h2><div id="rankMatches" class="rfgrid"></div><div class="savebar"><button class="btn primary" id="saveRank">💾 SALVAR 12 PARTIDAS</button><button class="btn" id="resetRank">↺ RESETAR REGISTRO</button></div></div><h2 style="margin-top:35px">📊 TABELA DO CAMPEONATO</h2><div class="rfwrap"><table class="rftable"><thead><tr><th>#</th><th>TIME</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>PTS</th></tr></thead><tbody id="rankBody"></tbody></table></div>';main.appendChild(s);s.querySelector('#saveRank').onclick=saveRank;s.querySelector('#resetRank').onclick=resetRank}rankTable()}
add();
})();