(() => {
  const SUPA_URL='https://vgurvbdbpxcgkhmunlxr.supabase.co';
  const SUPA_KEY='sb_publishable_Dlgj0c5D_PVKP0h7x6GZ4w_BssxbIoj';
  const API=SUPA_URL+'/rest/v1/artilheiros';
  const RPC=SUPA_URL+'/rest/v1/rpc/artilheiros_password_action';
  const HEAD={apikey:SUPA_KEY,Authorization:'Bearer '+SUPA_KEY,'Content-Type':'application/json'};
  let rows=[];
  let unlocked=false;
  const originalShowPage=window.showPage;
  function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
  function addStyles(){if(document.getElementById('artPasswordStyles'))return;const st=document.createElement('style');st.id='artPasswordStyles';st.textContent='.art-pass-overlay{position:fixed;inset:0;background:rgba(0,0,0,.82);display:flex;align-items:center;justify-content:center;z-index:9999;padding:20px}.art-pass-box{width:min(420px,100%);background:#121720;border:1px solid #343b47;border-radius:16px;padding:28px;box-shadow:0 20px 60px #000}.art-pass-box h2{margin-top:0;color:#ff7300}.art-pass-box input{width:100%;padding:13px;margin:8px 0;background:#080b10;color:#fff;border:1px solid #343b47;border-radius:8px;font-size:16px}.art-pass-box .err{color:#ff7373;min-height:24px}.art-pass-actions{display:flex;gap:10px;margin-top:12px}.art-pass-actions button{flex:1}.art-pass-help{color:#9aa3b0;font-size:13px}';document.head.appendChild(st)}
  function addUI(){
    const nav=document.getElementById('nav'),main=document.querySelector('main.wrap'); if(!nav||!main)return;
    addStyles();
    if(!document.getElementById('artilheirosNav')){const b=document.createElement('button');b.id='artilheirosNav';b.dataset.page='artilheiros';b.textContent='⚽ Artilheiros';b.addEventListener('click',()=>openProtected());nav.appendChild(b)}
    if(!document.getElementById('artilheiros')){const s=document.createElement('section');s.id='artilheiros';s.className='page';s.innerHTML='<h1>⚽ Artilheiros</h1><p class="muted">Cadastre o nome do jogador e a quantidade de gols.</p><div class="card"><div id="artilheirosGrid" class="slots"></div><div class="savebar"><button id="saveArtilheiros" class="btn primary">💾 Salvar artilheiros</button><span id="artilheirosMsg" class="ok"></span></div></div>';main.appendChild(s);document.getElementById('saveArtilheiros').addEventListener('click',save)}
  }
  async function rpc(action,password){const r=await fetch(RPC,{method:'POST',headers:HEAD,body:JSON.stringify({p_action:action,p_password:password})});if(!r.ok)throw new Error(await r.text());return await r.json()}
  function modal(html){return new Promise(resolve=>{const o=document.createElement('div');o.className='art-pass-overlay';o.innerHTML='<div class="art-pass-box">'+html+'</div>';document.body.appendChild(o);resolve(o)})}
  async function openProtected(){
    addUI();
    if(unlocked){originalShowPage('artilheiros');await load();return}
    let exists=false;try{exists=!!(await rpc('status',null))}catch(e){alert('Não foi possível verificar a senha. Tente novamente.');return}
    const first=!exists;
    const o=await modal(first?'<h2>🔐 Criar senha</h2><p class="muted">Na primeira entrada, escolha uma senha para proteger a aba Artilheiros.</p><input id="artPass1" type="password" placeholder="Nova senha (mínimo 4 caracteres)" autocomplete="new-password"><input id="artPass2" type="password" placeholder="Confirme a senha" autocomplete="new-password"><div class="err" id="artPassErr"></div><div class="art-pass-actions"><button class="btn" id="artPassCancel">Cancelar</button><button class="btn primary" id="artPassOk">Criar senha</button></div>':'<h2>🔐 Artilheiros protegidos</h2><p class="muted">Digite sua senha para entrar.</p><input id="artPass1" type="password" placeholder="Senha" autocomplete="current-password"><div class="err" id="artPassErr"></div><div class="art-pass-actions"><button class="btn" id="artPassCancel">Cancelar</button><button class="btn primary" id="artPassOk">Entrar</button></div>');
    o.querySelector('#artPassCancel').onclick=()=>o.remove();
    o.querySelector('#artPassOk').onclick=async()=>{const p=o.querySelector('#artPass1').value,err=o.querySelector('#artPassErr');err.textContent='';if(p.length<4){err.textContent='A senha precisa ter pelo menos 4 caracteres.';return}if(first&&p!==o.querySelector('#artPass2').value){err.textContent='As senhas não são iguais.';return}const btn=o.querySelector('#artPassOk');btn.disabled=true;btn.textContent='Verificando...';try{const ok=await rpc(first?'setup':'login',p);if(!ok){err.textContent=first?'Não foi possível criar a senha.':'Senha incorreta.';btn.disabled=false;btn.textContent=first?'Criar senha':'Entrar';return}o.remove();unlocked=true;originalShowPage('artilheiros');await load()}catch(e){console.error(e);err.textContent='Erro ao verificar a senha.';btn.disabled=false;btn.textContent=first?'Criar senha':'Entrar'}};
    o.querySelector('#artPass1').focus();
  }
  window.showPage=function(id){if(id==='artilheiros'){openProtected();return}unlocked=false;return originalShowPage(id)};
  async function load(){addUI();const grid=document.getElementById('artilheirosGrid');if(!grid)return;grid.innerHTML='<p class="muted">Carregando artilheiros...</p>';try{const r=await fetch(API+'?select=id,player_name,goals&order=id.asc',{headers:HEAD,cache:'no-store'});if(!r.ok)throw new Error(await r.text());rows=await r.json();while(rows.length<30)rows.push({id:null,player_name:'',goals:0});render()}catch(e){console.error(e);grid.innerHTML='<p class="muted">Não foi possível carregar os artilheiros.</p>'}}
  function render(){const grid=document.getElementById('artilheirosGrid');grid.innerHTML=rows.slice(0,30).map((r,i)=>'<label class="slot"><span class="num">'+(i+1)+'</span><input class="input artilheiroName" data-i="'+i+'" value="'+esc(r.player_name||'')+'" placeholder="Nome do jogador"><input class="input artilheiroGoals" data-i="'+i+'" type="number" min="0" value="'+Math.max(0,Number(r.goals)||0)+'" placeholder="Gols" style="max-width:120px"></label>').join('')}
  async function save(){if(!unlocked){openProtected();return}const msg=document.getElementById('artilheirosMsg');msg.textContent='Salvando...';try{const names=document.querySelectorAll('.artilheiroName'),goals=document.querySelectorAll('.artilheiroGoals');for(let i=0;i<names.length;i++){const row=rows[i],body={player_name:names[i].value.trim(),goals:Math.max(0,Number(goals[i].value)||0),updated_at:new Date().toISOString()};let r;if(row&&row.id)r=await fetch(API+'?id=eq.'+row.id,{method:'PATCH',headers:{...HEAD,Prefer:'return=minimal'},body:JSON.stringify(body)});else r=await fetch(API,{method:'POST',headers:{...HEAD,Prefer:'return=representation'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text())}msg.textContent='✓ Artilheiros salvos no site!';await load();setTimeout(()=>msg.textContent='',3000)}catch(e){console.error(e);msg.textContent='✕ Erro ao salvar';alert('Não foi possível salvar os artilheiros.')}}
  addUI();
})();
