(()=>{
const U='https://vgurvbdbpxcgkhmunlxr.supabase.co',K='sb_publishable_Dlgj0c5D_PVKP0h7x6GZ4w_BssxbIoj',MATCH=U+'/rest/v1/team_rank_matches',H={apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json'};
const TEAMS=['FENIX','RAFAGEMER','LOBO MAU','REAL MADRI','BARCELONA','ATLETICO DE MADRI','XV DE PIRACICABA','KATATUMBA','VERA CRUZ','NAPOLI','FIORENTINA','CRISTIAN SORTE'];
const LOGOS={'FENIX':'media/fenix.jpg','KATATUMBA':'media/katatumba.jpg','VERA CRUZ':'media/vera-cruz.jpg','REAL MADRI':'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg','BARCELONA':'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg','NAPOLI':'https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Neapel.svg','LOBO MAU':'https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg'};
const LOCAL={'RAFAGEMER':'☠️','ATLETICO DE MADRI':'🔴⚪','XV DE PIRACICABA':'⚫⚪','FIORENTINA':'⚜️','CRISTIAN SORTE':'🍀'};
let matches=[];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function emptyStats(){let s={};TEAMS.forEach(t=>s[t]={team:t,j:0,v:0,e:0,d:0,sg:0,pts:0});return s}
function calcStats(list){let s=emptyStats();list.forEach(m=>{let a=String(m.team_a||'').trim().toUpperCase(),b=String(m.team_b||'').trim().toUpperCase();if(!a||!b||a===b)return;if(!s[a])s[a]={team:a,j:0,v:0,e:0,d:0,sg:0,pts:0};if(!s[b])s[b]={team:b,j:0,v:0,e:0,d:0,sg:0,pts:0};let x=Math.max(0,+m.score_a||0),y=Math.max(0,+m.score_b||0);s[a].j++;s[b].j++;s[a].sg+=x-y;s[b].sg+=y-x;if(x>y){s[a].v++;s[b].d++;s[a].pts+=3;s[b].pts--}else if(y>x){s[b].v++;s[a].d++;s[b].pts+=3;s[a].pts--}else{s[a].e++;s[b].e++;s[a].pts++;s[b].pts++}});return s}
function stats(){return Object.values(calcStats(matches)).sort((a,b)=>b.pts-a.pts||b.sg-a.sg||b.v-a.v||TEAMS.indexOf(a.team)-TEAMS.indexOf(b.team))}
function css(){if(document.getElementById('rankTimesCss'))return;let s=document.createElement('style');s.id='rankTimesCss';s.textContent='.rfbox{background:#121720;border:1px solid #29313d;border-radius:15px;padding:20px}.rfgrid{display:grid;gap:10px}.rfmatch{display:grid;grid-template-columns:45px 1fr 70px 20px 70px 1fr;gap:8px;align-items:center}.rftable{width:100%;border-collapse:collapse;min-width:700px}.rftable th,.rftable td{padding:12px;border-bottom:1px solid #29313d;text-align:center}.rftable th{color:#ff7300}.rfwrap{overflow:auto}.teamcell{display:flex;align-items:center;gap:10px}.teamlogo,.teamfallback{width:34px;height:34px;object-fit:contain;border-radius:4px;background:#fff}.teamfallback{display:inline-flex;align-items:center;justify-content:center;font-size:21px;line-height:1}@media(max-width:650px){.rfmatch{grid-template-columns:25px 1fr 50px 12px 50px 1fr}.rfmatch input{padding:9px 4px;font-size:12px}.teamlogo,.teamfallback{width:30px;height:30px}}';document.head.appendChild(s)}
function rankUI(){let m=document.getElementById('rankMatches');if(!m)return;m.innerHTML=Array.from({length:18},(_,i)=>'<div class="rfmatch"><b class="orange">J'+(i+1)+'</b><input class="input ra" value="" placeholder="TIME A"><input class="input rsa" type="number" min="0" value="0"><b>×</b><input class="input rsb" type="number" min="0" value="0"><input class="input rb" value="" placeholder="TIME B"></div>').join('')}
function rankTable(){let t=document.getElementById('rankBody');if(!t)return;t.innerHTML=stats().map((x,i)=>{let logo=LOGOS[x.team]?'<img class="teamlogo" src="'+LOGOS[x.team]+'" alt="Escudo '+esc(x.team)+'">':LOCAL[x.team]?'<span class="teamfallback" title="'+esc(x.team)+'">'+LOCAL[x.team]+'</span>':'';return '<tr><td>'+(i+1)+'</td><td style="text-align:left"><span class="teamcell">'+logo+'<b>'+esc(x.team)+'</b></span></td><td>'+x.j+'</td><td>'+x.v+'</td><td>'+x.e+'</td><td>'+x.d+'</td><td>'+(x.sg>=0?'+':'')+x.sg+'</td><td class="points">'+x.pts+'</td></tr>'}).join('')}
async function loadRank(){try{let r=await fetch(MATCH+'?select=id,team_a,score_a,score_b,team_b&order=id.asc',{headers:H,cache:'no-store'});matches=r.ok?await r.json():[]}catch(e){matches=[]}rankUI();rankTable()}
async function saveRank(){let a=document.querySelectorAll('.ra'),b=document.querySelectorAll('.rb'),x=document.querySelectorAll('.rsa'),y=document.querySelectorAll('.rsb'),saved=0;for(let i=0;i<18;i++){let teamA=a[i].value.trim(),teamB=b[i].value.trim(),scoreA=Math.max(0,+x[i].value||0),scoreB=Math.max(0,+y[i].value||0);if(!teamA||!teamB||teamA.toUpperCase()===teamB.toUpperCase())continue;let body={team_a:teamA,score_a:scoreA,score_b:scoreB,team_b:teamB,updated_at:new Date().toISOString()};let rr=await fetch(MATCH,{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(body)});if(rr.ok)saved++}await loadRank();if(saved)alert(saved+' partida(s) adicionada(s) ao histórico acumulado.');else alert('Preencha pelo menos uma partida válida.')}
function resetRank(){if(!confirm('Resetar somente os 18 campos de registro? A TABELA ACUMULADA NÃO SERÁ APAGADA.'))return;rankUI();rankTable()}
function showRank(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));let p=document.getElementById('rank-times');if(p)p.classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='rank-times'));loadRank()}
function add(){css();let nav=document.getElementById('nav'),main=document.querySelector('main.wrap');if(!nav||!main)return;if(!document.getElementById('rankNav')){let b=document.createElement('button');b.id='rankNav';b.dataset.page='rank-times';b.textContent='🏆 RANK DOS TIMES';b.onclick=showRank;nav.appendChild(b)}if(!document.getElementById('rank-times')){let s=document.createElement('section');s.id='rank-times';s.className='page';s.innerHTML='<h1>🏆 RANK DOS TIMES</h1><p class="muted">Tabela permanente e acumulativa do campeonato.</p><div class="rfbox"><h2>⚽ REGISTRO DE 18 PARTIDAS</h2><p class="muted">Cada partida salva é adicionada permanentemente à tabela. O reset limpa somente estes campos.</p><div id="rankMatches" class="rfgrid"></div><div class="savebar"><button class="btn primary" id="saveRank">💾 SALVAR PARTIDAS</button><button class="btn" id="resetRank">↺ RESETAR REGISTRO</button></div></div><h2 style="margin-top:35px">📊 RANK DOS TIMES</h2><div class="rfwrap"><table class="rftable"><thead><tr><th>#</th><th>TIME</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>PTS</th></tr></thead><tbody id="rankBody"></tbody></table></div>';main.appendChild(s);s.querySelector('#saveRank').onclick=saveRank;s.querySelector('#resetRank').onclick=resetRank}rankTable()}
add();
})();