(()=>{
const U='https://vgurvbdbpxcgkhmunlxr.supabase.co',K='sb_publishable_Dlgj0c5D_PVKP0h7x6GZ4w_BssxbIoj',MATCH=U+'/rest/v1/team_rank_matches',H={apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json'};
const BASE_TEAMS=['FENIX','RAFAGAMER','LOBO MAU','REAL MADRI','BARCELONA','ATLETICO DE MADRI','XV DE PIRACICABA','KATATUMBA','VERA CRUZ','NAPOLI','FIORENTINA','CRISTIAN SORTE'];
let TEAMS=[];
const LOGOS={'FENIX':'media/fenix.jpg','RAFAGAMER':'media/rafagamer-flag.svg','KATATUMBA':'media/katatumba.jpg','VERA CRUZ':'media/vera-cruz.jpg','REAL MADRI':'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg','BARCELONA':'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg','ATLETICO DE MADRI':'https://en.wikinews.org/wiki/Special:Redirect/file/Atletico_Madrid_logo.svg','XV DE PIRACICABA':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Esporte_Clube_XV_de_Novembro_de_Piracicaba_logo.svg','NAPOLI':'https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Neapel.svg','LOBO MAU':'https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg','BOCA JUNIORS':'https://upload.wikimedia.org/wikipedia/commons/e/e3/Boca_Juniors_logo18.svg','BAYERN DE MUNCHEN':'https://commons.wikimedia.org/wiki/Special:Redirect/file/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg','BAYERN DE MUNIQUE':'https://commons.wikimedia.org/wiki/Special:Redirect/file/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg','SAO PAULO':'https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%A3o_Paulo_Futebol_Clube_logo_%282022%29.svg','SÃO PAULO':'https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%A3o_Paulo_Futebol_Clube_logo_%282022%29.svg','LAZIO':'https://commons.wikimedia.org/wiki/Special:Redirect/file/S.S._Lazio_logo.svg','SOBERANO':'https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%A3o_Paulo_Futebol_Clube_logo_%282022%29.svg','BAYERN':'https://commons.wikimedia.org/wiki/Special:Redirect/file/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg','BOCAJUNIORS':'https://upload.wikimedia.org/wikipedia/commons/e/e3/Boca_Juniors_logo18.svg'};
const LOCAL={'FIORENTINA':'⚜️','CRISTIAN SORTE':'☘'};
let matches=[];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function loadTeams(){let custom=[],deleted=[];try{custom=JSON.parse(localStorage.getItem('bombaRankCustomTeams')||'[]');deleted=JSON.parse(localStorage.getItem('bombaRankDeletedTeams')||'[]')}catch(e){}custom=custom.map(t=>t==='RAFAGEMER'?'RAFAGAMER':t);deleted=deleted.filter(t=>t!=='RAFAGAMER'&&t!=='RAFAGEMER');TEAMS=[...BASE_TEAMS.filter(t=>!deleted.includes(t)),...custom.filter(t=>!deleted.includes(t)&&!BASE_TEAMS.includes(t))]}
function saveTeamLists(custom,deleted){localStorage.setItem('bombaRankCustomTeams',JSON.stringify(custom));localStorage.setItem('bombaRankDeletedTeams',JSON.stringify(deleted));loadTeams()}
function emptyStats(){let s={};TEAMS.forEach(t=>s[t]={team:t,j:0,v:0,e:0,d:0,sg:0,pts:0});return s}
function calcStats(list){let s=emptyStats();list.forEach(m=>{let a=String(m.team_a||'').trim().toUpperCase(),b=String(m.team_b||'').trim().toUpperCase();if(a==='RAFAGEMER')a='RAFAGAMER';if(b==='RAFAGEMER')b='RAFAGAMER';if(!a||!b||a===b||!TEAMS.includes(a)||!TEAMS.includes(b))return;let x=Math.max(0,+m.score_a||0),y=Math.max(0,+m.score_b||0);s[a].j++;s[b].j++;s[a].sg+=x-y;s[b].sg+=y-x;if(x>y){s[a].v++;s[b].d++;s[a].pts+=3;s[b].pts--}else if(y>x){s[b].v++;s[a].d++;s[b].pts+=3;s[a].pts--}else{s[a].e++;s[b].e++;s[a].pts++;s[b].pts++}});return s}
function stats(){return Object.values(calcStats(matches)).sort((a,b)=>b.pts-a.pts||b.sg-a.sg||b.v-a.v||TEAMS.indexOf(a.team)-TEAMS.indexOf(b.team))}
function css(){if(document.getElementById('rankTimesCss'))return;let s=document.createElement('style');s.id='rankTimesCss';s.textContent='.rfbox{background:#121720;border:1px solid #29313d;border-radius:15px;padding:20px}.rfgrid{display:grid;gap:10px}.rfmatch{display:grid;grid-template-columns:45px 1fr 70px 20px 70px 1fr;gap:8px;align-items:center}.rftable{width:100%;border-collapse:collapse;min-width:760px}.rftable th,.rftable td{padding:12px;border-bottom:1px solid #29313d;text-align:center}.rftable th{color:#ff7300}.rfwrap{overflow:auto}.teamcell{display:flex;align-items:center;gap:10px}.teamlogo,.teamfallback{width:34px;height:34px;object-fit:contain;border-radius:4px;background:#fff}.teamfallback{display:inline-flex;align-items:center;justify-content:center;font-size:21px;line-height:1}.teamfallback[data-team="CRISTIAN SORTE"]{color:#168cff;font-size:29px;font-family:Arial,sans-serif;font-weight:bold}.teamlogo[alt="Escudo RAFAGAMER"]{width:46px;background:#050505}.dangerRank,.deleteTeam{background:#a91e1e!important;color:#fff!important;border-color:#d83b3b!important}.teamtools{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:15px 0 20px}.teamtools .input{max-width:330px}.deleteTeam{padding:7px 10px;font-size:12px}.rankNameError{border:2px solid #ff3b30!important;background:#2b0d0d!important;box-shadow:0 0 0 2px rgba(255,59,48,.15)}@media(max-width:650px){.rfmatch{grid-template-columns:25px 1fr 50px 12px 50px 1fr}.rfmatch input{padding:9px 4px;font-size:12px}.teamlogo,.teamfallback{width:30px;height:30px}.teamlogo[alt="Escudo RAFAGAMER"]{width:42px}}';document.head.appendChild(s)}
function rankUI(){let m=document.getElementById('rankMatches');if(!m)return;m.innerHTML=Array.from({length:18},(_,i)=>'<div class="rfmatch"><b class="orange">J'+(i+1)+'</b><input class="input ra" value="" placeholder="TIME A" list="rankTeamNames"><input class="input rsa" type="number" min="0" value="0"><b>×</b><input class="input rsb" type="number" min="0" value="0"><input class="input rb" value="" placeholder="TIME B" list="rankTeamNames"></div>').join('');let dl=document.getElementById('rankTeamNames');if(dl)dl.innerHTML=TEAMS.map(t=>'<option value="'+esc(t)+'"></option>').join('')}
function rankTable(){let t=document.getElementById('rankBody');if(!t)return;t.innerHTML=stats().map((x,i)=>{let logo=LOGOS[x.team]?'<img class="teamlogo" src="'+LOGOS[x.team]+'" alt="Escudo '+esc(x.team)+'">':LOCAL[x.team]?'<span class="teamfallback" data-team="'+esc(x.team)+'" title="'+esc(x.team)+'">'+LOCAL[x.team]+'</span>':'<span class="teamfallback">⚽</span>';return '<tr><td>'+(i+1)+'</td><td style="text-align:left"><span class="teamcell">'+logo+'<b>'+esc(x.team)+'</b></span></td><td>'+x.j+'</td><td>'+x.v+'</td><td>'+x.e+'</td><td>'+x.d+'</td><td>'+(x.sg>=0?'+':'')+x.sg+'</td><td class="points">'+x.pts+'</td><td><button class="btn deleteTeam" data-delete-team="'+esc(x.team)+'">🗑️ DELETAR</button></td></tr>'}).join('');t.querySelectorAll('[data-delete-team]').forEach(b=>b.onclick=()=>deleteTeam(b.dataset.deleteTeam))}
function createTeam(){let inp=document.getElementById('newRankTeam'),name=String(inp?.value||'').trim().toUpperCase();if(!name)return alert('Digite o nome do time.');if(TEAMS.includes(name))return alert('Esse time já está na tabela.');let custom=[],deleted=[];try{custom=JSON.parse(localStorage.getItem('bombaRankCustomTeams')||'[]');deleted=JSON.parse(localStorage.getItem('bombaRankDeletedTeams')||'[]')}catch(e){}deleted=deleted.filter(t=>t!==name);if(!BASE_TEAMS.includes(name)&&!custom.includes(name))custom.push(name);saveTeamLists(custom,deleted);inp.value='';rankUI();rankTable();alert('Time '+name+' criado na tabela.')}
function deleteTeam(name){if(!confirm('Deletar '+name+' da tabela do Rank dos Times?'))return;let custom=[],deleted=[];try{custom=JSON.parse(localStorage.getItem('bombaRankCustomTeams')||'[]');deleted=JSON.parse(localStorage.getItem('bombaRankDeletedTeams')||'[]')}catch(e){}custom=custom.filter(t=>t!==name);if(!deleted.includes(name))deleted.push(name);saveTeamLists(custom,deleted);rankUI();rankTable()}
async function loadRank(){loadTeams();try{let r=await fetch(MATCH+'?select=id,team_a,score_a,score_b,team_b&order=id.asc',{headers:H,cache:'no-store'});matches=r.ok?await r.json():[]}catch(e){matches=[]}rankUI();rankTable()}
async function saveRank(){let a=[...document.querySelectorAll('.ra')],b=[...document.querySelectorAll('.rb')],x=[...document.querySelectorAll('.rsa')],y=[...document.querySelectorAll('.rsb')];document.querySelectorAll('.rankNameError').forEach(el=>el.classList.remove('rankNameError'));let pending=[],errors=[];for(let i=0;i<18;i++){let rawA=a[i].value.trim(),rawB=b[i].value.trim(),teamA=rawA.toUpperCase(),teamB=rawB.toUpperCase(),scoreA=Math.max(0,+x[i].value||0),scoreB=Math.max(0,+y[i].value||0);if(!rawA&&!rawB)continue;if(!rawA||!rawB){if(!rawA){a[i].classList.add('rankNameError');errors.push('J'+(i+1)+': falta o TIME A')}if(!rawB){b[i].classList.add('rankNameError');errors.push('J'+(i+1)+': falta o TIME B')}continue}if(!TEAMS.includes(teamA)){a[i].classList.add('rankNameError');errors.push('J'+(i+1)+': "'+rawA+'" não existe na tabela')}if(!TEAMS.includes(teamB)){b[i].classList.add('rankNameError');errors.push('J'+(i+1)+': "'+rawB+'" não existe na tabela')}if(teamA===teamB){a[i].classList.add('rankNameError');b[i].classList.add('rankNameError');errors.push('J'+(i+1)+': o mesmo time não pode jogar contra ele mesmo')}if(TEAMS.includes(teamA)&&TEAMS.includes(teamB)&&teamA!==teamB)pending.push({team_a:teamA,score_a:scoreA,score_b:scoreB,team_b:teamB,updated_at:new Date().toISOString()})}if(errors.length){alert('⚠️ NÃO FOI POSSÍVEL SALVAR.\n\nCorrija os nomes destacados em vermelho:\n\n'+errors.join('\n')+'\n\nUse exatamente os nomes dos times cadastrados no Rank dos Times. Nenhuma partida foi salva.');return}if(!pending.length)return alert('Preencha pelo menos uma partida válida.');let saved=0;for(const body of pending){let rr=await fetch(MATCH,{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(body)});if(rr.ok)saved++;else{alert('Erro ao salvar as partidas. Foram salvas '+saved+' de '+pending.length+'.');await loadRank();return}}await loadRank();alert(saved+' partida(s) adicionada(s) ao histórico acumulado.')}
function resetRank(){if(!confirm('Resetar somente os 18 campos de registro? A TABELA ACUMULADA NÃO SERÁ APAGADA.'))return;rankUI();rankTable()}
async function resetRankTable(){if(!confirm('ATENÇÃO: isso vai apagar TODAS as partidas salvas e zerar completamente o Rank dos Times. Os times serão mantidos. Deseja continuar?'))return;if(!confirm('Última confirmação: apagar definitivamente todos os resultados?'))return;try{let r=await fetch(MATCH+'?id=not.is.null',{method:'DELETE',headers:{...H,Prefer:'return=minimal'}});if(!r.ok)throw new Error('Falha ao apagar');matches=[];rankUI();rankTable();alert('Resultados zerados. Os times foram mantidos.')}catch(e){alert('Não foi possível resetar a tabela. Nenhum dado foi alterado pelo site.')}}
function showRank(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));let p=document.getElementById('rank-times');if(p)p.classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='rank-times'));loadRank()}
function add(){loadTeams();css();let nav=document.getElementById('nav'),main=document.querySelector('main.wrap');if(!nav||!main)return;if(!document.getElementById('rankNav')){let b=document.createElement('button');b.id='rankNav';b.dataset.page='rank-times';b.textContent='🏆 RANK DOS TIMES';b.onclick=showRank;nav.appendChild(b)}if(!document.getElementById('rank-times')){let s=document.createElement('section');s.id='rank-times';s.className='page';s.innerHTML='<h1>🏆 RANK DOS TIMES</h1><p class="muted">Tabela permanente e acumulativa do campeonato.</p><div class="rfbox"><h2>⚽ REGISTRO DE 18 PARTIDAS</h2><p class="muted">Digite os nomes exatamente como aparecem no Rank dos Times. Se houver nome incorreto, nenhuma partida será salva.</p><datalist id="rankTeamNames"></datalist><div id="rankMatches" class="rfgrid"></div><div class="savebar"><button class="btn primary" id="saveRank">💾 SALVAR PARTIDAS</button><button class="btn" id="resetRank">↺ RESETAR REGISTRO</button><button class="btn dangerRank" id="resetRankTable">🗑️ RESETAR TABELA</button></div></div><h2 style="margin-top:35px">📊 RANK DOS TIMES</h2><div class="teamtools"><input id="newRankTeam" class="input" placeholder="NOME DO NOVO TIME"><button class="btn primary" id="createRankTeam">➕ CRIAR TIME</button></div><div class="rfwrap"><table class="rftable"><thead><tr><th>#</th><th>TIME</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>PTS</th><th>AÇÃO</th></tr></thead><tbody id="rankBody"></tbody></table></div>';main.appendChild(s);s.querySelector('#saveRank').onclick=saveRank;s.querySelector('#resetRank').onclick=resetRank;s.querySelector('#resetRankTable').onclick=resetRankTable;s.querySelector('#createRankTeam').onclick=createTeam}rankTable()}
add();
})();