(()=>{
const U='https://vgurvbdbpxcgkhmunlxr.supabase.co',K='sb_publishable_Dlgj0c5D_PVKP0h7x6GZ4w_BssxbIoj',MATCH=U+'/rest/v1/team_rank_matches',H={apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json'};
const TEAMS=['FENIX','RAFAGEMER','LOBO MAU','REAL MADRI','BARCELONA','ATLETICO DE MADRI','XV DE PIRACICABA','KATATUMBA','VERA CRUZ','NAPOLI','FIORENTINA','CRISTIAN SORTE'];
const svg=s=>'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(s);
const LOGOS={
'REAL MADRI':'https://image.pngaaa.com/818/449818-middle.png',
'BARCELONA':'https://image.pngaaa.com/147/639147-middle.png',
'ATLETICO DE MADRI':'https://toppng.com/uploads/preview/athletic-club-madrid-vector-logo-11573984807h8en2zfzsn.png',
'NAPOLI':'https://www.liblogo.com/img-logo/ss4950sa04-ssc-napoli-logo-s-s-c-napoli-liblogo.png',
'FIORENTINA':'https://toppng.com/uploads/preview/fiorentina-logo-vector-download-free-11574194510etzotaum0h.png',
'LOBO MAU':'https://images.fotmob.com/image_resources/logo/teamlogo/8602.png',
'XV DE PIRACICABA':'https://www.google.com/s2/favicons?domain=xvpiracicaba.com.br&sz=128',
'VERA CRUZ':'https://www.google.com/s2/favicons?domain=seeklogo.com&sz=128',
'RAFAGEMER':'https://www.vhv.rs/dpng/d/213-2136287_transparent-pirate-logo-png-straw-hat-logo-png.png',
'KATATUMBA':'https://acdn-us.mitiendanube.com/stores/002/260/329/products/camiseta-katatumba-piracicaba-fractalmw-fractalmusicwear-fractal-music-wear-piracicaba1-5bbd4cc2b643022de216617951232461-1024-1024.webp',
'FENIX':svg('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text x="50" y="75" text-anchor="middle" font-size="72">🔥</text></svg>'),
'CRISTIAN SORTE':svg('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><g fill="#168cff"><circle cx="35" cy="35" r="22"/><circle cx="65" cy="35" r="22"/><circle cx="35" cy="65" r="22"/><circle cx="65" cy="65" r="22"/><rect x="47" y="50" width="10" height="43" rx="5" transform="rotate(-25 52 72)"/></g></svg>')};
let matches=[];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function emptyStats(){let s={};TEAMS.forEach(t=>s[t]={team:t,j:0,v:0,e:0,d:0,sg:0,pts:0});return s}
function calcStats(list){let s=emptyStats();list.forEach(m=>{let a=String(m.team_a||'').trim().toUpperCase(),b=String(m.team_b||'').trim().toUpperCase();if(!a||!b||a===b)return;if(!s[a])s[a]={team:a,j:0,v:0,e:0,d:0,sg:0,pts:0};if(!s[b])s[b]={team:b,j:0,v:0,e:0,d:0,sg:0,pts:0};let x=Math.max(0,+m.score_a||0),y=Math.max(0,+m.score_b||0);s[a].j++;s[b].j++;s[a].sg+=x-y;s[b].sg+=y-x;if(x>y){s[a].v++;s[b].d++;s[a].pts+=3;s[b].pts--}else if(y>x){s[b].v++;s[a].d++;s[b].pts+=3;s[a].pts--}else{s[a].e++;s[b].e++;s[a].pts++;s[b].pts++}});return s}
function stats(){return Object.values(calcStats(matches)).sort((a,b)=>b.pts-a.pts||b.sg-a.sg||b.v-a.v||TEAMS.indexOf(a.team)-TEAMS.indexOf(b.team))}
function css(){if(document.getElementById('rankTimesCss'))return;let s=document.createElement('style');s.id='rankTimesCss';s.textContent='.rfbox{background:#121720;border:1px solid #29313d;border-radius:15px;padding:20px}.rfgrid{display:grid;gap:10px}.rfmatch{display:grid;grid-template-columns:45px 1fr 70px 20px 70px 1fr;gap:8px;align-items:center}.rftable{width:100%;border-collapse:collapse;min-width:700px}.rftable th,.rftable td{padding:12px;border-bottom:1px solid #29313d;text-align:center}.rftable th{color:#ff7300}.rfwrap{overflow:auto}.rfteam{display:flex;align-items:center;gap:10px}.rfcrest{width:34px;height:34px;object-fit:contain;flex:0 0 34px;border-radius:4px}@media(max-width:650px){.rfmatch{grid-template-columns:25px 1fr 50px 12px 50px 1fr}.rfmatch input{padding:9px 4px;font-size:12px}.rfcrest{width:28px;height:28px;flex-basis:28px}}';document.head.appendChild(s)}
function rankUI(){let m=document.getElementById('rankMatches');if(!m)return;m.innerHTML=Array.from({length:18},(_,i)=>'<div class="rfmatch"><b class="orange">J'+(i+1)+'</b><input class="input ra" value="" placeholder="TIME A"><input class="input rsa" type="number" min="0" value="0"><b>×</b><input class="input rsb" type="number" min="0" value="0"><input class="input rb" value="" placeholder="TIME B"></div>').join('')}
function rankTable(){let t=document.getElementById('rankBody');if(!t)return;t.innerHTML=stats().map((x,i)=>{let logo=LOGOS[x.team]||'';return '<tr><td>'+(i+1)+'</td><td style="text-align:left"><span class="rfteam">'+(logo?'<img class="rfcrest" src="'+esc(logo)+'" alt="Escudo '+esc(x.team)+'" loading="lazy">':'')+'<b>'+esc(x.team)+'</b></span></td><td>'+x.j+'</td><td>'+x.v+'</td><td>'+x.e+'</td><td>'+x.d+'</td><td>'+(x.sg>=0?'+':'')+x.sg+'</td><td class="points">'+x.pts+'</td></tr>'}).join('')}
async function loadRank(){try{let r=await fetch(MATCH+'?select=id,team_a,score_a,score_b,team_b&order=id.asc',{headers:H,cache:'no-store'});matches=r.ok?await r.json():[]}catch(e){matches=[]}rankUI();rankTable()}
async function saveRank(){let a=document.querySelectorAll('.ra'),b=document.querySelectorAll('.rb'),x=document.querySelectorAll('.rsa'),y=document.querySelectorAll('.rsb'),saved=0;for(let i=0;i<18;i++){let teamA=a[i].value.trim(),teamB=b[i].value.trim(),scoreA=Math.max(0,+x[i].value||0),scoreB=Math.max(0,+y[i].value||0);if(!teamA||!teamB||teamA.toUpperCase()===teamB.toUpperCase())continue;let body={team_a:teamA,score_a:scoreA,score_b:scoreB,team_b:teamB,updated_at:new Date().toISOString()};let rr=await fetch(MATCH,{method:'POST',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(body)});if(rr.ok)saved++}await loadRank();if(saved)alert(saved+' partida(s) adicionada(s) ao histórico acumulado.');else alert('Preencha pelo menos uma partida válida.')}
function resetRank(){if(!confirm('Resetar somente os 18 campos de registro? A TABELA ACUMULADA NÃO SERÁ APAGADA.'))return;rankUI();rankTable()}
function showRank(){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));let p=document.getElementById('rank-times');if(p)p.classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='rank-times'));loadRank()}
function add(){css();let nav=document.getElementById('nav'),main=document.querySelector('main.wrap');if(!nav||!main)return;if(!document.getElementById('rankNav')){let b=document.createElement('button');b.id='rankNav';b.dataset.page='rank-times';b.textContent='🏆 RANK DOS TIMES';b.onclick=showRank;nav.appendChild(b)}if(!document.getElementById('rank-times')){let s=document.createElement('section');s.id='rank-times';s.className='page';s.innerHTML='<h1>🏆 RANK DOS TIMES</h1><p class="muted">Tabela permanente e acumulativa do campeonato.</p><div class="rfbox"><h2>⚽ REGISTRO DE 18 PARTIDAS</h2><p class="muted">Cada partida salva é adicionada permanentemente à tabela. O reset limpa somente estes campos.</p><div id="rankMatches" class="rfgrid"></div><div class="savebar"><button class="btn primary" id="saveRank">💾 SALVAR PARTIDAS</button><button class="btn" id="resetRank">↺ RESETAR REGISTRO</button></div></div><h2 style="margin-top:35px">📊 RANK DOS TIMES</h2><div class="rfwrap"><table class="rftable"><thead><tr><th>#</th><th>TIME</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>PTS</th></tr></thead><tbody id="rankBody"></tbody></table></div>';main.appendChild(s);s.querySelector('#saveRank').onclick=saveRank;s.querySelector('#resetRank').onclick=resetRank}rankTable()}
add();
})();