(()=>{const b=document.createElement('script');b.src='tactics-base.js';document.head.appendChild(b);const a=document.createElement('script');a.src='artilheiros.js';document.head.appendChild(a)})();
const PLAYER_PAIRS=[['R','B'],['R','C'],['R','L'],['B','C'],['B','L'],['C','L']],HISTORY_API=SUPA+'/rest/v1/bomba_petch_history';let historyData=[],historySelected=0,tableSyncing=false;
function ensureGamePlayers(){games.forEach((g,i)=>{const p=PLAYER_PAIRS[i%6];if(!g.player_a)g.player_a=p[0];if(!g.player_b)g.player_b=p[1]})}
function calculateStandings(){ensureGamePlayers();const s={R:{name:'R',j:0,w:0,d:0,l:0,pts:0},B:{name:'B',j:0,w:0,d:0,l:0,pts:0},C:{name:'C',j:0,w:0,d:0,l:0,pts:0},L:{name:'L',j:0,w:0,d:0,l:0,pts:0}};games.forEach(g=>{const A=String(g.player_a||'').toUpperCase(),B=String(g.player_b||'').toUpperCase(),a=Number(g.score_a),b=Number(g.score_b);if(!s[A]||!s[B]||A===B||!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<0||a===0&&b===0)return;s[A].j++;s[B].j++;if(a>b){s[A].w++;s[A].pts+=3;s[B].l++;s[B].pts--}else if(b>a){s[B].w++;s[B].pts+=3;s[A].l++;s[A].pts--}else{s[A].d++;s[B].d++;s[A].pts++;s[B].pts++}});return['R','B','C','L'].map(k=>s[k])}
function renderTableRows(rows){const t=document.getElementById('tableBody');if(!t)return;const o=['R','B','C','L'],r=[...(rows||[])].map(x=>({name:String(x.name||''),j:Number(x.j)||0,w:Number(x.w)||0,d:Number(x.d)||0,l:Number(x.l)||0,pts:Number(x.pts)||0})).sort((a,b)=>b.pts-a.pts||b.w-a.w||b.j-a.j||o.indexOf(a.name)-o.indexOf(b.name));tableSyncing=true;t.innerHTML=r.map((x,i)=>`<tr><td>${i+1}º</td><td>${esc(x.name)}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td class="points">${x.pts}</td></tr>`).join('');setTimeout(()=>tableSyncing=false,0)}
function syncPermanentTable(){if(historyData.length)renderTableRows(historyData[historyData.length-1].snapshot)}
function updateMatchStandings(){const r=calculateStandings(),t=document.getElementById('standingsBody');if(t)t.innerHTML=r.map(x=>`<tr><td>${x.name}</td><td>${x.j}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td class="points">${x.pts}</td></tr>`).join('');if(!historyData.length)renderTableRows(r);else syncPermanentTable()}window.renderStandings=updateMatchStandings;
function historyTableHTML(r){return `<div class="standings"><table><thead><tr><th>Jogador</th><th>J</th><th>V</th><th>E</th><th>D</th><th>Pontos</th></tr></thead><tbody>${(r||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.j||0}</td><td>${x.w||0}</td><td>${x.d||0}</td><td>${x.l||0}</td><td class="points">${x.pts||0}</td></tr>`).join('')}</tbody></table></div>`}
function renderHistory(){const box=document.getElementById('history');if(!box)return;const intro='<h1>📜 História</h1><div class="card"><p>O BOMBA PETCH é disputado por <b>Rafagamer, Cristian, Leandro e Berna</b>.</p><p class="muted">As tabelas ficam registradas aqui quando um campeonato é resetado.</p></div>';if(!historyData.length){box.innerHTML=intro+'<div class="card" style="margin-top:20px"><h2>🏆 Primeiro Campeonato Da Temporada</h2><p class="muted">Ainda não há campeonato encerrado.</p></div>';return}const tabs=historyData.map((h,i)=>`<button class="btn ${i===historySelected?'primary':''}" data-history="${i}">🏆 ${esc(h.title)}</button>`).join(''),h=historyData[historySelected]||historyData[0];box.innerHTML=intro+`<div style="display:flex;gap:10px;flex-wrap:wrap;margin:20px 0">${tabs}</div><div class="card"><h2>${esc(h.title)}</h2><p class="muted">Registrado em ${h.created_at?new Date(h.created_at).toLocaleString('pt-BR'):''}</p>${historyTableHTML(h.snapshot)}</div>`;box.querySelectorAll('[data-history]').forEach(x=>x.onclick=()=>{historySelected=+x.dataset.history;renderHistory()})}
async function loadHistory(){try{const r=await fetch(HISTORY_API+'?select=id,title,snapshot,created_at&order=id.asc',{headers:H});if(!r.ok)throw Error(await r.text());historyData=await r.json();historySelected=Math.max(0,historyData.length-1);syncPermanentTable()}catch(e){console.error(e);historyData=[]}renderHistory()}
async function saveHistorySnapshot(){const snapshot=calculateStandings();try{const q=await fetch(HISTORY_API+'?select=id&order=id.desc&limit=1',{headers:H});if(!q.ok)throw Error(await q.text());const old=await q.json(),n=(old.length?+old[0].id:0)+1,ords=['Primeiro','Segundo','Terceiro','Quarto','Quinto','Sexto','Setimo','Oitavo','Nono','Decimo'],title=`${ords[n-1]||n+'º'} Campeonato Da Temporada`;const r=await fetch(HISTORY_API,{method:'POST',headers:{...HJSON,Prefer:'return=representation'},body:JSON.stringify({title,snapshot})});if(!r.ok)throw Error(await r.text());const z=await r.json();historyData.push(z[0]||{title,snapshot,created_at:new Date().toISOString()});historySelected=historyData.length-1;syncPermanentTable();renderHistory();return true}catch(e){console.error(e);alert('Não foi possível salvar a tabela na História. O reset não foi realizado.');return false}}
const obs=new MutationObserver(()=>{clearTimeout(window.__bombaTableTimer);window.__bombaTableTimer=setTimeout(updateMatchStandings,0)});const permObs=new MutationObserver(()=>{if(tableSyncing||!historyData.length)return;clearTimeout(window.__bombaPermanentTimer);window.__bombaPermanentTimer=setTimeout(syncPermanentTable,0)});setTimeout(()=>{const x=document.getElementById('standingsBody');if(x)obs.observe(x,{childList:true,subtree:true});const y=document.getElementById('tableBody');if(y)permObs.observe(y,{childList:true,subtree:true});updateMatchStandings();loadHistory()},0);
document.addEventListener('input',e=>{const x=e.target;if(!x.classList||!x.classList.contains('gameInput'))return;const i=+x.dataset.i;if(!games[i])return;const p=PLAYER_PAIRS[i%6];games[i].player_a=p[0];games[i].player_b=p[1];clearTimeout(window.__bombaInputTimer);window.__bombaInputTimer=setTimeout(updateMatchStandings,0)},true);
async function persistPlayerOwners(){ensureGamePlayers();try{for(const g of games){const r=await fetch(GAMES+'?id=eq.'+g.id,{method:'PATCH',headers:{...HJSON,Prefer:'return=minimal'},body:JSON.stringify({player_a:g.player_a,player_b:g.player_b})});if(!r.ok)throw Error(await r.text())}}catch(e){console.error(e)}}
document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('#saveGames');if(b){ensureGamePlayers();setTimeout(persistPlayerOwners,1200)}},true);
async function hydratePlayerOwners(){ensureGamePlayers();try{const r=await fetch(GAMES+'?select=id,player_a,player_b&order=id.asc',{headers:H});if(r.ok)(await r.json()).forEach(x=>{if(x.id>=1&&x.id<=18){const i=x.id-1,p=PLAYER_PAIRS[i%6];games[i].player_a=String(x.player_a||p[0]).toUpperCase();games[i].player_b=String(x.player_b||p[1]).toUpperCase()}});updateMatchStandings();await persistPlayerOwners()}catch(e){console.error(e)}}setTimeout(hydratePlayerOwners,900);
const resetGamesButton=document.getElementById('resetGames');if(resetGamesButton)resetGamesButton.addEventListener('click',async e=>{e.stopImmediatePropagation();if(!confirm('Salvar a tabela atual na História e depois resetar apenas as partidas?'))return;if(!await saveHistorySnapshot())return;games.forEach((g,i)=>{const p=PLAYER_PAIRS[i%6];g.player_a=p[0];g.player_b=p[1];g.team_a=p[0];g.team_b=p[1];g.score_a=0;g.score_b=0});renderGames();updateMatchStandings();syncPermanentTable();try{for(const g of games){const r=await fetch(GAMES+'?id=eq.'+g.id,{method:'PATCH',headers:{...HJSON,Prefer:'return=minimal'},body:JSON.stringify({team_a:g.team_a,score_a:0,score_b:0,team_b:g.team_b,player_a:g.player_a,player_b:g.player_b,updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text())}const m=document.getElementById('gamesMsg');if(m){m.textContent='✓ Partidas resetadas. A aba Tabela foi preservada!';setTimeout(()=>m.textContent='',4000)}}catch(err){console.error(err)}},true);

// Aba Jornal Bomba Petch
function createJournalTab(){const nav=document.getElementById('nav'),main=document.querySelector('main.wrap');if(!nav||!main||document.getElementById('journal'))return;const btn=document.createElement('button');btn.dataset.page='journal';btn.textContent='📰 Jornal Bomba Petch';nav.appendChild(btn);const sec=document.createElement('section');sec.id='journal';sec.className='page';sec.innerHTML=`<h1>📰 Jornal Bomba Petch</h1><p class="muted">Notícias, resultados e acontecimentos do BOMBA PETCH.</p><div class="cards" style="margin-top:20px"><div class="card"><div class="orange"><b>📰 EDIÇÃO ATUAL</b></div><h2>Jornal Bomba Petch</h2><p>O espaço oficial para registrar as notícias e os grandes momentos dos campeonatos.</p></div><div class="card"><div class="orange"><b>🏆 CAMPEONATOS</b></div><h2>Resultados e classificação</h2><p>Acompanhe as partidas, campeonatos e evolução dos jogadores.</p></div><div class="card"><div class="orange"><b>⭐ DESTAQUES</b></div><h2>Os protagonistas</h2><p>Rafagamer, Cristian, Berna e Leandro ganham espaço nas manchetes.</p></div></div><div class="card" style="margin-top:20px"><h2>📢 Últimas notícias</h2><div id="journalNews"><p class="muted">Nenhuma notícia cadastrada ainda.</p></div></div></section>`;main.appendChild(sec);btn.onclick=()=>showPage('journal')}
setTimeout(createJournalTab,0);