const TACTIC_FORMATIONS={"5-4-1":[[50,91,"GOL"],[18,78,"LAT"],[38,82,"ZAG"],[62,82,"ZAG"],[82,78,"LAT"],[25,61,"MEI"],[42,65,"MEI"],[58,65,"MEI"],[75,61,"MEI"],[50,27,"ATA"]],"4-3-3":[[50,91,"GOL"],[20,76,"LAT"],[40,82,"ZAG"],[60,82,"ZAG"],[80,76,"LAT"],[30,59,"MEI"],[50,64,"MEI"],[70,59,"MEI"],[24,32,"ATA"],[50,25,"ATA"],[76,32,"ATA"]],"3-5-2":[[50,91,"GOL"],[28,78,"ZAG"],[50,82,"ZAG"],[72,78,"ZAG"],[12,58,"ALA"],[32,62,"MEI"],[50,66,"MEI"],[68,62,"MEI"],[88,58,"ALA"],[38,29,"ATA"],[62,29,"ATA"]],"4-4-2":[[50,91,"GOL"],[20,76,"LAT"],[40,82,"ZAG"],[60,82,"ZAG"],[80,76,"LAT"],[20,57,"MEI"],[40,61,"MEI"],[60,61,"MEI"],[80,57,"MEI"],[38,31,"ATA"],[62,31,"ATA"]],"4-2-3-1":[[50,91,"GOL"],[20,76,"LAT"],[40,82,"ZAG"],[60,82,"ZAG"],[80,76,"LAT"],[38,61,"VOL"],[62,61,"VOL"],[25,43,"MEI"],[50,38,"MEI"],[75,43,"MEI"],[50,25,"ATA"]],"3-4-3":[[50,91,"GOL"],[28,79,"ZAG"],[50,83,"ZAG"],[72,79,"ZAG"],[18,59,"ALA"],[40,63,"MEI"],[60,63,"MEI"],[82,59,"ALA"],[24,31,"ATA"],[50,25,"ATA"],[76,31,"ATA"]],"5-3-2":[[50,91,"GOL"],[14,76,"LAT"],[32,82,"ZAG"],[50,84,"ZAG"],[68,82,"ZAG"],[86,76,"LAT"],[30,59,"MEI"],[50,64,"MEI"],[70,59,"MEI"],[38,30,"ATA"],[62,30,"ATA"]],"4-5-1":[[50,91,"GOL"],[20,76,"LAT"],[40,82,"ZAG"],[60,82,"ZAG"],[80,76,"LAT"],[18,57,"MEI"],[34,61,"MEI"],[50,64,"MEI"],[66,61,"MEI"],[82,57,"MEI"],[50,27,"ATA"]]};
let currentTactic='4-3-3';
function tacticsKey(){return 'bomba-petch-tactics-'+((window.selectedPlayer&&window.selectedPlayer.code)||'global');}
function renderTactics(){const host=document.getElementById('tacticsHost');if(!host)return;host.innerHTML='<div class="tactics-panel"><h2>🧠 TÁTICAS</h2><p class="muted">Escolha uma formação para visualizar o time no campo.</p><div class="tactics-tabs">'+Object.keys(TACTIC_FORMATIONS).map(f=>'<button type="button" class="'+(f===currentTactic?'active':'')+'" data-tactic="'+f+'">'+f+'</button>').join('')+'</div><div id="tacticsPitch" class="pitch"></div><div class="tactics-actions"><button type="button" class="btn primary" id="saveTacticsBtn">💾 Salvar tática</button><span id="tacticsMsg" class="tactics-msg"></span></div></div>';host.querySelectorAll('[data-tactic]').forEach(b=>b.onclick=()=>{currentTactic=b.dataset.tactic;renderTactics()});const pitch=document.getElementById('tacticsPitch');pitch.innerHTML=TACTIC_FORMATIONS[currentTactic].map((p,i)=>'<div class="tplayer" style="left:'+p[0]+'%;top:'+p[1]+'%"><span>'+String(i+1)+'</span><input id="tactic-'+i+'" placeholder="'+p[2]+'"></div>').join('');try{const data=JSON.parse(localStorage.getItem(tacticsKey())||'{}')[currentTactic]||[];data.forEach((v,i)=>{const el=document.getElementById('tactic-'+i);if(el)el.value=v})}catch(e){}document.getElementById('saveTacticsBtn').onclick=saveTactics;}
function saveTactics(){const vals=TACTIC_FORMATIONS[currentTactic].map((_,i)=>document.getElementById('tactic-'+i)?.value||'');const data=JSON.parse(localStorage.getItem(tacticsKey())||'{}');data[currentTactic]=vals;localStorage.setItem(tacticsKey(),JSON.stringify(data));const m=document.getElementById('tacticsMsg');m.textContent='✓ Tática salva neste dispositivo!';setTimeout(()=>m.textContent='',2500)}
function ensureTactics(){const pc=document.getElementById('profileContent');if(!pc)return;if(!document.getElementById('tacticsHost')){const host=document.createElement('div');host.id='tacticsHost';pc.appendChild(host)}renderTactics();renderPlayerList()}
window.ensureTactics=ensureTactics;
const SUPABASE_URL='https://vgurvbdbpxcgkhmunlxr.supabase.co';
const SUPABASE_KEY='sb_publishable_Dlgj0c5D_PVKP0h7x6GZ4w_BssxbIoj';
const GENERAL_LIST_URL=SUPABASE_URL+'/rest/v1/general_player_list';
const GENERAL_HEADERS={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'};
function renderPlayerList(){const pc=document.getElementById('profileContent');if(!pc||document.getElementById('playerListHost'))return;const host=document.createElement('div');host.id='playerListHost';host.innerHTML='<div class="card player-list-card"><h2>📋 LISTA DE JOGADORES</h2><p class="muted">Lista independente dos times. Edite os nomes e os times que quiser.</p><div class="player-list-sections"></div><div class="savebar"><button type="button" class="btn primary" id="savePlayerList">💾 Salvar lista</button><span id="playerListMsg" class="ok"></span></div></div>';pc.appendChild(host);const sections=host.querySelector('.player-list-sections');const cats=[['🧤 Goleiros','goleiros',10],['🛡️ Zagueiros','zagueiros',30],['↔️ Laterais','laterais',20],['⚙️ Volantes','volantes',15],['🎯 Meio-campo','meio-campo',30],['⚡ Atacantes','atacantes',40]];sections.innerHTML=cats.map(([label,key,count])=>'<div class="position"><h3>'+label+' ('+count+')</h3><div class="slots">'+Array.from({length:count},(_,i)=>'<label class="slot"><span class="num">'+(i+1)+'</span><input class="input playerListInput" data-category="'+key+'" data-slot="'+(i+1)+'" placeholder="Digite o jogador"><input class="input playerTeamInput" data-category="'+key+'" data-slot="'+(i+1)+'" placeholder="Time do jogador"></label>').join('')+'</div></div>').join('');loadGeneralPlayerList(host);host.querySelector('#savePlayerList').onclick=()=>saveGeneralPlayerList(host)}
async function loadGeneralPlayerList(host){try{const r=await fetch(GENERAL_LIST_URL+'?select=category,slot_number,player_name,team_name&order=category,slot_number',{headers:GENERAL_HEADERS,cache:'no-store'});if(!r.ok)throw new Error(await r.text());const rows=await r.json();host.querySelectorAll('.playerListInput').forEach(i=>{const row=rows.find(x=>x.category===i.dataset.category&&Number(x.slot_number)===Number(i.dataset.slot));if(row)i.value=row.player_name||''});host.querySelectorAll('.playerTeamInput').forEach(i=>{const row=rows.find(x=>x.category===i.dataset.category&&Number(x.slot_number)===Number(i.dataset.slot));if(row)i.value=row.team_name||''})}catch(e){console.error('Erro ao carregar lista:',e)}}
async function saveGeneralPlayerList(host){const msg=host.querySelector('#playerListMsg');msg.textContent='Salvando...';const rows=[];host.querySelectorAll('.playerListInput').forEach(i=>{const team=host.querySelector('.playerTeamInput[data-category="'+i.dataset.category+'"][data-slot="'+i.dataset.slot+'"]');rows.push({category:i.dataset.category,slot_number:Number(i.dataset.slot),player_name:i.value.trim(),team_name:team?team.value.trim():'',updated_at:new Date().toISOString()})});try{const r=await fetch(GENERAL_LIST_URL+'?on_conflict=category,slot_number',{method:'POST',headers:{...GENERAL_HEADERS,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)});if(!r.ok)throw new Error(await r.text());msg.textContent='✓ Lista salva no site!';await loadGeneralPlayerList(host);setTimeout(()=>msg.textContent='',2500)}catch(e){console.error('Erro ao salvar lista:',e);msg.textContent='✕ Erro ao salvar';alert('Não foi possível salvar a lista de jogadores.')}}
function bindProfileButtons(){const cards=document.querySelectorAll('#profileCards [data-player]');cards.forEach(card=>{if(card.dataset.profileBound==='1')return;card.dataset.profileBound='1';card.addEventListener('click',function(e){e.preventDefault();const code=this.dataset.player;if(window.players&&typeof window.openProfile==='function'){const player=window.players.find(p=>p.code===code);if(player)window.openProfile(player)}else if(typeof openProfile==='function'&&typeof players!=='undefined'){const player=players.find(p=>p.code===code);if(player)openProfile(player)}})})}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{try{if(typeof renderProfiles==='function')renderProfiles()}catch(e){console.error('Erro ao renderizar perfis:',e)}bindProfileButtons()},50)});
window.bindProfileButtons=bindProfileButtons;
const profileObserver=new MutationObserver(()=>{const pc=document.getElementById('profileContent');if(!pc)return;const code=pc.querySelector('.profile-head .big')?.textContent?.trim();if(code){window.currentProfileCode=code;setTimeout(()=>{try{ensureTactics()}catch(e){console.error('Erro ao carregar lista/táticas:',e)}},0)}});
const profileRoot=document.getElementById('profileContent');
if(profileRoot)profileObserver.observe(profileRoot,{childList:true,subtree:true});
(function(){
 const cats=[['🧤 Goleiros','goleiros',10],['🛡️ Zagueiros','zagueiros',30],['↔️ Laterais','laterais',20],['⚙️ Volantes','volantes',15],['🎯 Meio-campo','meio_campo',30],['⚡ Atacantes','atacantes',40]];
 function addTab(){const nav=document.getElementById('nav');if(!nav||document.getElementById('playersListNav'))return;const b=document.createElement('button');b.id='playersListNav';b.dataset.page='playersList';b.textContent='📋 Lista de Jogadores';b.addEventListener('click',()=>showPage('playersList'));nav.appendChild(b)}
 function addPage(){const main=document.querySelector('main.wrap');if(!main||document.getElementById('playersList'))return;const s=document.createElement('section');s.id='playersList';s.className='page';s.innerHTML='<h1>📋 Lista de Jogadores</h1><p class="muted">10 goleiros, 30 zagueiros, 20 laterais, 15 volantes, 30 meio-campo e 40 atacantes. Informe o nome do jogador e o time em que ele joga.</p><div id="generalPlayerList"></div><div class="savebar"><button id="saveGeneralPlayerList" class="btn primary">💾 Salvar lista</button><span id="generalPlayerListMsg" class="ok"></span></div>';main.appendChild(s);renderPage()}
 async function renderPage(){const host=document.getElementById('generalPlayerList');if(!host)return;host.innerHTML=cats.map(([label,key,count])=>'<div class="card" style="margin-top:20px"><h2>'+label+' ('+count+')</h2><div class="slots">'+Array.from({length:count},(_,i)=>'<label class="slot"><span class="num">'+(i+1)+'</span><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;width:100%"><input class="input generalName" data-cat="'+key+'" data-i="'+i+'" placeholder="Nome do jogador"><input class="input generalTeam" data-cat="'+key+'" data-i="'+i+'" placeholder="Time do jogador"></div></label>').join('')+'</div></div>').join('');try{const r=await fetch(GENERAL_LIST_URL+'?select=category,slot_number,player_name,team_name&order=category,slot_number',{headers:GENERAL_HEADERS,cache:'no-store'});if(r.ok){const rows=await r.json();host.querySelectorAll('.generalName').forEach(i=>{const row=rows.find(x=>x.category===i.dataset.cat&&Number(x.slot_number)===Number(i.dataset.i)+1);if(row)i.value=row.player_name||''});host.querySelectorAll('.generalTeam').forEach(i=>{const row=rows.find(x=>x.category===i.dataset.cat&&Number(x.slot_number)===Number(i.dataset.i)+1);if(row)i.value=row.team_name||''})}}catch(e){console.error('Erro ao carregar lista geral:',e)}}
 async function savePage(){const host=document.getElementById('generalPlayerList');const msg=document.getElementById('generalPlayerListMsg');if(!host||!msg)return;msg.textContent='Salvando...';const rows=[];host.querySelectorAll('.generalName').forEach(i=>{const team=host.querySelector('.generalTeam[data-cat="'+i.dataset.cat+'"][data-i="'+i.dataset.i+'"]');rows.push({category:i.dataset.cat,slot_number:Number(i.dataset.i)+1,player_name:i.value.trim(),team_name:team?team.value.trim():'',updated_at:new Date().toISOString()})});try{const r=await fetch(GENERAL_LIST_URL+'?on_conflict=category,slot_number',{method:'POST',headers:{...GENERAL_HEADERS,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)});if(!r.ok)throw new Error(await r.text());msg.textContent='✓ Lista salva no site!';await renderPage();setTimeout(()=>msg.textContent='',2500)}catch(e){console.error('Erro ao salvar lista geral:',e);msg.textContent='✕ Erro ao salvar';alert('Não foi possível salvar a lista de jogadores.')}}
 document.addEventListener('DOMContentLoaded',()=>{addTab();addPage();setTimeout(()=>{const b=document.getElementById('saveGeneralPlayerList');if(b)b.addEventListener('click',savePage)},100)});
})();